# Generated by Django 2.2.3 on 2019-09-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=10),
            preserve_default=False,
        ),
    ]
